name: Chrome headless

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      - name: Cypress run
      - uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/e2e/feedback.spec.js
