name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          spec: cypress/integration/e2e/*.spec.js
          browser: chrome
