name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
    uses: actions/setup-node@v1
      
  - name: Install dependencies
    run: npm install
      
  - name: Checkout
      uses: actions/checkout@v1

  - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        spec: cypress/integration/e2e/feedback.spec.js
